name = "stall-tcp-13-v1"
main = "_worker.js"
compatibility_date = "2025-12-17"
# D1 数据库绑定
d1_databases = [
  { binding = "DB", database_name = "huo-db", database_id = "d4f7-8e-45c7-afd-7c60a" }
]

